import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { v4 as uuidv4 } from 'uuid';

// Set up the S3 client with your AWS region
const s3 = new S3Client({
    region: "us-east-1", // Specify your AWS region here
    credentials: {
        accessKeyId: process.env.AWS_ACCESS_KEY_ID,
        secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
    },
});

const bucketName = process.env.AWS_S3_BUCKET_NAME;

// Upload image to S3
export const uploadToS3 = async (fileBuffer) => {
    try {
        // Generate a unique key for the file using uuid
        const uniqueKey = `${uuidv4()}-${file.originalname}`;

        // Create the file stream
        const fileStream = file.buffer;

        const params = {
            Bucket: bucketName,     // S3 bucket name
            Key: uniqueKey,         // the unique key generated by uuid
            Body: fileStream,       // The file data
            ContentType: "image/jpeg", // Set the appropriate content type for the file (e.g., image/jpeg)
        };

        // Create the PutObjectCommand
        const command = new PutObjectCommand(params);

        // Execute the command to upload the file to S3
        const data = await s3.send(command);
        console.log("File uploaded successfully", data);

        // return the S3 URL
        return `https://${bucketName}.s3.${s3.config.region}.amazonaws.com/${uniqueKey}`; 
    } catch (error) {
        console.error("Error uploading file", error);
        throw new Error("Failed to upload file to S3");
    }
};
